// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWxOG4S19cvaF0EQjZzQmEho-Wyi-klzk',
    appId: '1:538255187251:web:55ee2fcbfaf277dc037246',
    messagingSenderId: '538255187251',
    projectId: 'evacuateisucc',
    authDomain: 'evacuateisucc.firebaseapp.com',
    storageBucket: 'evacuateisucc.appspot.com',
    measurementId: 'G-F2YCWLTF13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqVox7dIhOZOXzd5k1abzj_o-GcqsAjSU',
    appId: '1:538255187251:android:3dec03b9c9e140e7037246',
    messagingSenderId: '538255187251',
    projectId: 'evacuateisucc',
    storageBucket: 'evacuateisucc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYfAKdNviLB7ck87IfRoIQpIlOjclgIgw',
    appId: '1:538255187251:ios:66421cbd0a4e3ac5037246',
    messagingSenderId: '538255187251',
    projectId: 'evacuateisucc',
    storageBucket: 'evacuateisucc.appspot.com',
    iosClientId: '538255187251-12qbauv6cq7cllnp4ie5taolt166h8ob.apps.googleusercontent.com',
    iosBundleId: 'com.example.evacuatem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYfAKdNviLB7ck87IfRoIQpIlOjclgIgw',
    appId: '1:538255187251:ios:66421cbd0a4e3ac5037246',
    messagingSenderId: '538255187251',
    projectId: 'evacuateisucc',
    storageBucket: 'evacuateisucc.appspot.com',
    iosClientId: '538255187251-12qbauv6cq7cllnp4ie5taolt166h8ob.apps.googleusercontent.com',
    iosBundleId: 'com.example.evacuatem',
  );
}
